### ISSUE TITLE
Setup and deploy to Production environment

### ISSUE THREAD

**Issue by alexstojda** [cfes-fceg/livevoting#16]
Setup and deploy to production environment

### Tasks
- [ ] Define release flow
- [ ] Setup release tagging process
- [ ] Setup production environment to deploy only on new tag creation

Blocked by #15
